# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Create Release Candidate v2"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      sem-ver:
        type: string
        description: Version number
        required: true
      payload:
        type: string
        description: JSON payload
        required: true


env:
  node-version: 16.14
  java-distribution: zulu
  java-version: 12
  flutter-version: 2.10.3

#####################################################################################
### ATTENTION: Make sure to test the release with all checks we also use for PRs! ###
#####################################################################################
jobs:
  logs-build-selection:
    name: Logs the selection for the current build
    runs-on: ubuntu-latest
    steps:
      - name: Update latest version in realtime database
        uses: w9jds/firebase-trigger@master
        with:
          credentials: ${{ secrets.FIRESTORE }}
          databaseUrl: https://firestore-test-9aa41.firebaseio.com
          path: tomato
          doc: ${{ github.event.inputs.sem-ver }}
          value: ${{ github.event.inputs.payload }}